# Generated by Django 5.2.6 on 2025-09-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(choices=[('TEXT', 'Text Fish'), ('IMG', 'Image Fish'), ('GIF', 'GIF Fish')], help_text='The type of fish reward, e.g., TEXT, IMG, or GIF.', max_length=4)),
                ('message', models.TextField(blank=True, help_text='Text message for text fish rewards.', null=True)),
                ('media_url', models.TextField(blank=True, help_text='File path or URL for image/gif rewards.', null=True)),
            ],
            options={
                'verbose_name': 'Fish Reward',
                'verbose_name_plural': 'Fish Rewards',
            },
        ),
        migrations.CreateModel(
            name='RedeemedFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_before_redeem', models.PositiveIntegerField(default=0, help_text='The number of clicks the user had before redeeming.')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp of when the reward was redeemed.')),
                ('fish_reward', models.ForeignKey(help_text='The specific fish reward assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.fishreward')),
                ('user', models.ForeignKey(help_text='The user who redeemed the reward.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redeemed Fish',
                'verbose_name_plural': 'Redeemed Fish',
            },
        ),
    ]
